# Done to increase the memory available to gradle
org.gradle.jvmargs=-Xmx3G
# Enable Gradle configuration cache
org.gradle.configuration-cache=true
# enable the remote build cache
org.gradle.caching=true

# Metadata
mod_id=odyssey
mod_description=Give any entity dialogue and the ability to grant quests to players
mod_display_name=Odyssey
sources_url=https://github.com/CammiesCorner/Odyssey
issues_url=https://github.com/CammiesCorner/Odyssey/issues
license_url=https://github.com/CammiesCorner/Odyssey/blob/HEAD/LICENSE.md
discord_url=https://cammiescorner.dev/discord
homepage_url=https://cammiescorner.dev

# Publishing
maven_group_id=dev.cammiescorner.odyssey
curseforge_id=0
modrinth_id=0
